#!/usr/bin/env python3
import re
import sqlite3
import sys

if len(sys.argv) != 3:
    raise SystemExit('Usage: convert_postgres_dump_to_sqlite.py INPUT_SQL OUTPUT_SQLITE')

input_sql, output_db = sys.argv[1:]
text = open(input_sql, encoding='utf-8').read()

# Keep only INSERT statements generated by pg_dump and adapt common PostgreSQL syntax.
statements = []
for match in re.finditer(r'INSERT INTO public\.([a-zA-Z_][a-zA-Z0-9_]*)\s*\([^;]+?\)\s*VALUES\s*\([^;]+?\);', text, re.S):
    statement = match.group(0)
    statement = statement.replace('INSERT INTO public.', 'INSERT INTO ')
    statement = re.sub(r'::[a-zA-Z_][a-zA-Z0-9_\[\]]*', '', statement)
    statement = statement.replace('TRUE', '1').replace('FALSE', '0')
    statements.append(statement)

if not statements:
    raise SystemExit('No INSERT statements found in PostgreSQL dump')

connection = sqlite3.connect(output_db)
try:
    connection.execute('PRAGMA foreign_keys = OFF')
    for statement in statements:
        connection.execute(statement)
    connection.commit()
    connection.execute('PRAGMA foreign_keys = ON')
finally:
    connection.close()

print(f'Imported {len(statements)} INSERT statements into {output_db}')
